### ISSUE TITLE
Provide setup instructions

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/unit_testing_Cpp#10]
`setup.py` should contain the instructions required for the attendees to the course to setup their computers to run the examples and do the exercises. 

This file can probably be populated in parallel to #2 and #7 .

**Comment by alexdewar** [comment]
I assume you mean `setup.md`? :wink:

I think we can now flesh this issue out a bit. There should be instructions for:

- Installing the compiler and an appropriate version of CMake (if needed)
- Downloading the source code
- Building the source code, to check that it all works and the student knows what they're doing
- *Possibly*: Instructions on how to run `ctest` (though if everything has built successfully, this step should work)
